# Generated by Django 6.0.3 on 2026-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('teacher_id', models.IntegerField()),
                ('standard', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('status', models.CharField(default='draft', max_length=20)),
            ],
        ),
    ]
